name=dorado-tag-editor
addonVersion=2.0
classifier=component
depends=dorado-core[7.1.18,*]
contextConfigLocations=com.bstek.dorado.tageditor.config.TagEditorContextConfig
componentConfigLocations=com.bstek.dorado.tageditor.config.TagEditorComponentsConfig