name=dorado-console
addonVersion=2.0
configurer=com.bstek.dorado.console.ConsolePackageConfigurer
contextConfigLocations=
componentConfigLocations=
servletContextConfigLocations=com.bstek.dorado.console.ConsoleRequiredServletContextConfig
propertiesConfigLocations=
servletContextListener=