name=dorado-core
version=8.1.0
majorVersion=7
minorVersion=7
incrementalVersion=0
publication=240905.1153
qualifier=RELEASE
revision=8.1.0
addonVersion=2.0
configurer=
contextConfigLocations=com.bstek.dorado.core.CoreContextConfig,\
com.bstek.dorado.config.TextParserContextConfig,\
com.bstek.dorado.config.XmlParserContextConfig,\
com.bstek.dorado.common.CommonContextConfig,\
com.bstek.dorado.data.config.DataContextConfig,\
com.bstek.dorado.data.config.DataXmlParserContextConfig,\
com.bstek.dorado.web.WebContextConfig,\
com.bstek.dorado.view.config.ViewContextConfig,\
com.bstek.dorado.idesupport.IdeContextConfig
componentConfigLocations=com.bstek.dorado.core.CoreContextConfig,\
com.bstek.dorado.config.TextParserContextConfig,\
com.bstek.dorado.config.XmlParserContextConfig,\
com.bstek.dorado.common.CommonContextConfig,\
com.bstek.dorado.data.config.DataContextConfig,\
com.bstek.dorado.data.config.DataXmlParserContextConfig,\
com.bstek.dorado.web.WebContextConfig,\
com.bstek.dorado.view.config.ViewContextConfig,\
com.bstek.dorado.idesupport.IdeContextConfig
servletContextConfigLocations=com.bstek.dorado.web.WebServletContextConfig,\
com.bstek.dorado.view.config.ViewServletContextConfig,\
com.bstek.dorado.idesupport.IdeServletContextConfig
propertiesConfigLocations=
servletContextListener=
