version=1.0.20-SNAPSHOT

name=dorado-uploader
addonVersion=2.0
loadUnlicensed=false
depends=dorado-core
license=Inherited
classifier=http\://www.bstek.com
contextConfigLocations=com.bstek.dorado.uploader.config.UploaderContextConfig
servletContextConfigLocations=com.bstek.dorado.uploader.config.UploaderServletContextConfig
componentConfigLocations=com.bstek.dorado.uploader.config.UploaderComponentsConfig